// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"04-project-layout/app"
	"04-project-layout/internal/biz"
	"04-project-layout/internal/conf"
	"04-project-layout/internal/data"
	"04-project-layout/internal/server"
	"04-project-layout/internal/service"
	"github.com/go-kit/kit/log"
)

// Injectors from wire.go:

func createApp(cfg *conf.Config, logger log.Logger) (*app.App, error) {
	dataData, err := data.NewData(cfg, logger)
	if err != nil {
		return nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase, logger)
	grpcServer := server.NewGRPCServer(cfg, greeterService)
	appApp, err := newApp(grpcServer, cfg)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}
